version: "2.0"
services:
  app:
    build: 
      context: .
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:12
    env_file: .env
    ports:
      - 5432:5432


